name: Build & Release hezhijie0327/ContentFarm4SearXNG

on:
  schedule:
    - cron: "0 8,20 * * *" # UTC+8 04:00 / 16:00
  workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Step 1 - Checkout
              uses: actions/checkout@v3.1.0
            - name: Step 2 - Setup Python Environment
              uses: actions/setup-python@v4.3.0
              with:
                check-latest: true
                python-version: '3'
            - name: Step 3 - Install Pip Packages
              run: |
                  sudo pip install requests pyyaml argparse
            - name: Step 4 - Build ContentFarm4SearXNG
              run: |
                  sudo python "./hostname_generator.py"
            - name: Step 5 - Release ContentFarm4SearXNG
              run: |
                  curl -s "https://raw.githubusercontent.com/hezhijie0327/Toolkit/main/Git.sh" > "/tmp/Git.sh"
                  sudo bash "/tmp/Git.sh" -u "hezhijie0327" -e "hezhijie0327@hotmail.com" -f "." -r "ContentFarm4SearXNG" -i "Generated by GitHub Actions" -m "push"
